# Generated by Django 5.0.6 on 2024-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('semester', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('last_semester_gpa', models.FloatField()),
                ('credits', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
